spring:
  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: 123
    hikari:
      # 连接自动提交
      auto-commit: true
      # 连接池名
      pool-name: DataHikariCP
      # 最大连接数，默认 10
      maximum-pool-size: 10
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间，默认是 600000ms（10min）。这里设置 30min
      idle-timeout: 1800000
      # 连接最大存活时间，0表示永久存活，默认 1800000ms，即 30min
      max-lifetime: 1800000
      # 连接超时时间，默认 30000ms，即 30秒
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

# mybatis-plus配置
mybatis-plus:
  # 默认 private String[] mapperLocations = new String[]{"classpath*:/mapper/**/*.xml"};
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.engure.seckill.pojo

# 日志打印
logging:
  level:
    # sql打印，是 mapper 接口所在的包
    com.engure.seckill.mapper: debug
